"""Add profile picture field to User model

Revision ID: 33817bd2f9bd
Revises: 
Create Date: 2025-03-30 15:12:44.037915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33817bd2f9bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
